### ISSUE TITLE
 Cannot read property '_id' of undefined

### ISSUE THREAD

**Issue by Zaynex** [EchoLsx/movie#1]
```
exports.save = function(req, res) {
   console.log(req.body.movie);
  var id = req.body.movie._id;
  var movieObj = req.body.movie;
  var _movie;
```

不知道您有没有遇到过这个问题。在第二期电影录入分类中显示的报错信息。找不到_id。如果您遇到了，希望能告知，感谢

**Comment by EchoLsx** [comment]
查查数据库里面有没有记录，按我的猜想，估计数据库记录可能也没新增成功

**Comment by EchoLsx** [comment]
@Zaynex 是不是Cannot read property '_id' of undefined  ，我也遇到过
查查数据库里面有没有记录，按我的猜想，你这个估计数据库记录都没新增成功，可能是米admin.jade传参错误

**Comment by Zaynex** [comment]
@EchoLsx  是的，数据库里没有movie数据，我再检查下 admin.jade

**Comment by Zaynex** [comment]
@EchoLsx  你在本地测试的时候电影后台录入的速度如何？ 我这边几乎跑不动
